### ISSUE TITLE
[Question] Should active admin be added?

### ISSUE THREAD

**Issue by dacur** [rubyforgood/partner#60]
I was working on some specs, and noticed an index spec commented out (in partners requests), which then led me to a comment in a file saying something like "maybe we should add admins".

Adding active admin would be a quick and easy way to handle admin tasks, at least in the beginning.

**Comment by armahillo** [comment]
Chiming in here only to add my experience having used `ActiveAdmin` a bunch over the years (and even on the main `diaper` app!). Since I'm not a maintainer for this app I don't specifically have a dog in this fight, so do what you will. :)

 - I agree that `active_admin` is a great turnkey solution for quickly adding CRUD for the models
 - If you do choose to use it, be sure to set it up to NOT use the admin "notes" (these create a `notes` table). IIRC you can use `active_admin` without having any additional schema changes to your DB. 
 - If you want to do anything beyond basic CRUD, *immediately* begin planning an exit strategy to replace `active_admin` with custom-built stuff. You *can* do custom actions with `active_admin` but the technical debt piles up quickly
 - If you currently use an `admin` namespace, you will collide with `active_admin` (you can configure around this though)
 - I believe Thoughtbot also has `administrate` but I've not used it so I do not know how mature it is

You might be able to get similar ramping-up speed for admins by using rails scaffolding (skip migration, specify "admin" namespace) and then customizing from there. That would at least handle stubbing / initializing all the files you need.
